### ISSUE TITLE
Incorrectly displayed documentation for BatRandom

### ISSUE THREAD

**Issue by co-dan** [ocaml-batteries-team/batteries-included#883]

**Comment by co-dan** [comment]
The problem is in the style sheet:

```css
.superscript { font-size : 4 }
.subscript { font-size : 4 }
```

Firefox complains that `4` is not a valid argument, and defaults it to `4px`, which is very small.
